# Generated by Django 4.1 on 2022-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("SLS", "Sales"), ("SPP", "Support"), ("MNG", "Management")],
                default="SLS",
                max_length=3,
            ),
            preserve_default=False,
        ),
    ]
