# Generated by Django 4.1 on 2022-08-16 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_client_first_name_alter_client_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_contract",
                to="crm.client",
            ),
        ),
    ]
