# Generated by Django 4.1 on 2022-08-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_contract_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
